name: Build and publish wheels

on:
 workflow_dispatch:
 # push:
 #   tags:
 #     - '*'  # Triggers the workflow on version tags

permissions:
  contents: write
  actions: read
  
jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build SDist
        run: pipx run build --sdist

      - name: Check metadata
        run: pipx run twine check dist/*

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
 
  build_wheels:
    name: Build ${{ matrix.arch }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-11-arm
            arch: ARM64
          
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_SKIP: "*pp3* *cp38* *cp39* *cp310*"
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
          CIBW_ENVIRONMENT_MACOS:
            MACOSX_DEPLOYMENT_TARGET=${{ matrix.macos_deployment_target }}
          CIBW_TEST_REQUIRES: numpy==2.3.0rc1
          CIBW_TEST_COMMAND: |
           python -c "import skfmm, sys; sys.exit(skfmm.test())"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
          retention-days: 5
  
  
