name: Windows Build

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-11-arm
    strategy:
      matrix:
        python-version: ["3.11","3.12","3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: ARM64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy wheel
      - name: Build extension
        run: |
          python --version
          python -c "import struct; print(struct.calcsize('P') * 8)"
          pip install build
          python -m build
          pip install .
          pip list
      - uses: actions/upload-artifact@v4
        with:
          name: windows-arm-artifacts
          path: dist/*
      - name: Run skfmm tests
        run: |
          python -c 'import os; os.chdir(".."); import skfmm; print(skfmm.__version__)'
          python -c 'import os; os.chdir(".."); import skfmm, sys; sys.exit(skfmm.test())'
